/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FileService } from "../file.service";
import { FileCreateInput } from "./FileCreateInput";
import { File } from "./File";
import { FileFindManyArgs } from "./FileFindManyArgs";
import { FileWhereUniqueInput } from "./FileWhereUniqueInput";
import { FileUpdateInput } from "./FileUpdateInput";
import { LinkFindManyArgs } from "../../link/base/LinkFindManyArgs";
import { Link } from "../../link/base/Link";
import { LinkWhereUniqueInput } from "../../link/base/LinkWhereUniqueInput";

export class FileControllerBase {
  constructor(protected readonly service: FileService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: File })
  async createFile(@common.Body() data: FileCreateInput): Promise<File> {
    return await this.service.createFile({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        filename: true,
        fileType: true,
        fileUrl: true,
        id: true,
        updatedAt: true,
        uploadedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [File] })
  @ApiNestedQuery(FileFindManyArgs)
  async files(@common.Req() request: Request): Promise<File[]> {
    const args = plainToClass(FileFindManyArgs, request.query);
    return this.service.files({
      ...args,
      select: {
        createdAt: true,
        filename: true,
        fileType: true,
        fileUrl: true,
        id: true,
        updatedAt: true,
        uploadedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: File })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async file(
    @common.Param() params: FileWhereUniqueInput
  ): Promise<File | null> {
    const result = await this.service.file({
      where: params,
      select: {
        createdAt: true,
        filename: true,
        fileType: true,
        fileUrl: true,
        id: true,
        updatedAt: true,
        uploadedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: File })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFile(
    @common.Param() params: FileWhereUniqueInput,
    @common.Body() data: FileUpdateInput
  ): Promise<File | null> {
    try {
      return await this.service.updateFile({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          filename: true,
          fileType: true,
          fileUrl: true,
          id: true,
          updatedAt: true,
          uploadedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: File })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFile(
    @common.Param() params: FileWhereUniqueInput
  ): Promise<File | null> {
    try {
      return await this.service.deleteFile({
        where: params,
        select: {
          createdAt: true,
          filename: true,
          fileType: true,
          fileUrl: true,
          id: true,
          updatedAt: true,
          uploadedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/links")
  @ApiNestedQuery(LinkFindManyArgs)
  async findLinks(
    @common.Req() request: Request,
    @common.Param() params: FileWhereUniqueInput
  ): Promise<Link[]> {
    const query = plainToClass(LinkFindManyArgs, request.query);
    const results = await this.service.findLinks(params.id, {
      ...query,
      select: {
        createdAt: true,
        expiryDate: true,

        file: {
          select: {
            id: true,
          },
        },

        id: true,
        isActive: true,
        linkUrl: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/links")
  async connectLinks(
    @common.Param() params: FileWhereUniqueInput,
    @common.Body() body: LinkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      links: {
        connect: body,
      },
    };
    await this.service.updateFile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/links")
  async updateLinks(
    @common.Param() params: FileWhereUniqueInput,
    @common.Body() body: LinkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      links: {
        set: body,
      },
    };
    await this.service.updateFile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/links")
  async disconnectLinks(
    @common.Param() params: FileWhereUniqueInput,
    @common.Body() body: LinkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      links: {
        disconnect: body,
      },
    };
    await this.service.updateFile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/upload-file")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async UploadFile(
    @common.Body()
    body: string
  ): Promise<string> {
    return this.service.UploadFile(body);
  }

  @common.Get("/:id/upload-file")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async UploadFile(
    @common.Body()
    body: string
  ): Promise<string> {
    return this.service.UploadFile(body);
  }
}
